sudo: false
language: node_js
cache:
  directories:
    - node_modules
node_js:
  - '0.12'
  - v4
  - stable
after_success:
  - 'travis-after-all && npm run semantic-release'
env:
  global:
    - secure: Gy2iDRgEN7yWSgLZXFt9YaKRM93+jAZgKUV66TBQk7O+TeD71KnC/sZ0nGhCG50si0LBZCo4Wff5t/wNImaeuMqgmMQ/SKSsdMDW5nIEbAjbqn3ORTHHD/n70CA4dNyfKMgR/bkG4y+qxFLd2jhyw0gIraZXrhEvUVvf/N78BMAAgl9Arenkig6J2D2p07dtOZoMZzbwhb7LCXs7VVHcEe3fIjyDSchXola8eA9hsX1kSHEsfPn54DE2VbK+3PvdJPfZSlPuKanDKxwrCipYrrUym1g1jGgcDC/fKXXuBFvdOHEYt2AEe2EPAmST9KiX3aMFD8YthAXhYxNKFoKNYjLjL3gImjiKqbb6sWQE8P/4gtf+zsl8wju/blofqhvFrlYgP/RLiQAQagVEldzTzgiCyM0JaKQaf/TMeUjDlQ2LMPkvQy43uZewzgrHrQMiYT6eWySpWlwZ4vh9JpZ7DCuE+EvLH3iHabN00X3mMRuQvmdBBWdqFl4jm6EAdNBqkGk69bKGCsUYmqdvyKfw9wHwdK4uSZv5ko+11DV4Wb4T9ZW7/9k0SOzUiV2L5pTaguWYEl0c+cnHWSNBkH7f2JPHsSfjqbMY4TtV5LnhcxGWskooGAgrTUsjb4zTHgbXgm24YH4kHy7LcJ7kzyjSJNYhoRr7N4gejHc++C7TO1E=
    - secure: Kmd3ig2xfCa6yYlM0yh/GZmn3fl/imHT1KmPxP+e/km5EkTW1k/Y59BRawcOMg6mfdXdlOOO0B4vMCZXN2vq4h5BTuShujebDYjo5Ujfymm5HnCQxj8cDSoF19EzTBhqv9SaJF69JpLk9dyWdaScYd7GosNcZDeVj1accJu2b1LxNSM/i36CrEIBQ2RopwWYV3LgkaKCeiE3H93R+z2hmrGBdy0bUWjrjJJcc35csAcm4f1FB1gKulAvBRl20ySIWSuaNeUxgpuagyRGKBzsiA6301xOPpMbmY2XFBjd5axb1NjY85dUWv3iNyZcV46/G05ScBp3GSp9hVK0XoTinxuKMKv0eD0eDMJGHAz7yDKPa1nl5QMndj3D8ADSbc51kLhxIM3z3jz7AX6Ls/RkjZT6DAj4Y9C1V9vQNdQS3IB8PaGW+jnZgW6VYMmMo9kUdREGv77dO6+KwpPl+zO2EPCycNGKFkQdOY/EyVGJemS+iMXq+diIKpANgpdBbt4k8V7JmcAuNXBU78thw2vxUYIIItlX/lsLF9DYyMpUZSUzWXoTBh6fGcco9usLWPLyqGdmShhHlvGB2qXfobFIdLPbOEzLTip3+DlUHJ/d3vg8zuzHtMrg+1DfIEJqaWG1nG2URe2mXMAWzWyTfmxVdE47CNCguypet1FKcMGXZRQ=
