sudo: false
language: node_js
cache:
  directories:
    - node_modules
node_js:
  - '0.12'
  - v4
  - stable
after_success:
  - 'travis-after-all && npm run semantic-release'
env:
  global:
    - secure: RlIXFBVBN3qZnCPitL0JTWVjD6BlYLv9m0N1p0zwGKMQmIse3+9prSg0HzDW6DXysKcNKHHdJg13wO7wsS6qgYd9l0lQT9JQ6k6HbPUUcaZGuVNx8g/t9zxwFtQAsDqvzEuAkTNL/wA7acL13jXCyOtSiX/+cdI9lXLGAEKdfmUWMO1DK+BhdlF5ozgO/KH45oS4mASuyhofziEK26BijFoqqiDGqFateH98CBstbZ+s1JD3524wYZfREN3h56t3LVmedwmXacbcZgs0R4QtepiwKiVsITHGZWlMsA/p3rCJNBEl5kciVLj0N9GhOme5ZFKVe89+opzhEoy9Yxovnap5zQFiwl7t3/z/gz1o8XjpT6jcZTWdqWGChw4ryPmDvLtYH1wfHPB6ejUj4ZvIAnFzXUxHC4EPXWSTcBSkGWUsauvrUe2cRqmRhPzhdqRNltJ9bVYC4wfdZQR7gw2FzLVkclrgddmRjsOk7r00uyJXeOTEIQOJhrXFQit3l9peHZsmMer3oNB/xXPeY4hbY+FkuRh2CFa3zWUWZj0AgD0EZd6EEHxey2BaE0NyJIALWih7/DdiUr9SQE6FPsyyJTXQhlErIyNZgCQ7tu7H0NHjc5iKsZKXeybphcnOPsk6jzNjiZTLQPqtOPD8Ov5oZn1lytjv84glIg/pmpM1YY0=
    - secure: Q/+LS4NR/rMJlNpcsj/m8macDkguj4sCSum3JSsWLLd3G5IXSA/BCa/skmozu1OMrwVLZtGDM//2PvkXvljLnzU8mX3tf3tVvhHYAMrMrfsoCTJtkP2PFvSeP19Qz4qmmJgWty1j9+8KJppmklkuV/IUN0V/ZgDQXvC6RFBFBAqOJWD9q7cBiqAOowJAcl60HpnZAY5QpvAFKV5wybi8ZtI/LwuUaese2ysuDikJ4QlOjPnagzdPeZRDhcuReOMBs+ibF5x3wlGqwHF6BnCD3Vrt+pXzMLpvtX3rnwO5Uqq5CKrxpr0K0U1N+QPjU2S76OWhPcLAp2DYcqqoiDwGEFov350cBrGueGzgc4HKOe97ZPXvbVOs9CNwiQox75EGD1gDkKc96P09lfDLOjD2X7fXlmhLpuskXG4c3iyxXu6m26c+DkuWJK7Owkdkt6yBh7yLzwbzpZMBH+7M2qEZ83FacUKBS7Do709/etzBbUijOM8w1bAL1wlnwsYgI/2jPfJSCXY5CWzhkUFURlGF2EWKAO4rwpKD5dmLValO8beTmd+lq7bxpy3g8i+Cb6hy9A9NolLJeBTzK8+lCuSCRNkJsZPPZRpxlr8B6Lishc2YJ9dFSP2wSYV3b/AFa9v1ISpjFfcLpsuPTWjvM5mv83teJ1+gWrUVshsIiG98rFg=
